import localFont from "next/font/local"; // Importation de la fonction pour charger des polices locales dans une application Next.js.
import "./globals.css"; // Importation du fichier CSS global pour styliser l'ensemble de l'application.

const geistSans = localFont({
	src: "./fonts/GeistVF.woff", // Chemin vers la police sans serif (GeistVF).
	variable: "--font-geist-sans", // Déclaration d'une variable CSS pour utiliser cette police.
	weight: "100 900", // Définition de la plage de poids de la police (de 100 à 900).
});

const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff", // Chemin vers la police monospace (GeistMonoVF).
	variable: "--font-geist-mono", // Déclaration d'une variable CSS pour utiliser cette police.
	weight: "100 900", // Définition de la plage de poids de la police (de 100 à 900).
});

// Métadonnées pour la page (titre et description).
export const metadata = {
	title: "My Next Portfolio", // Titre de l'application affiché dans l'onglet du navigateur.
	description: "Generated by create next app", // Description de l'application, utilisée par les moteurs de recherche et les réseaux sociaux.
};

// Composant de mise en page racine de l'application.
export default function RootLayout({ children }) {
	return (
		<html lang="en">
			{" "}
			{/* Définition de la langue de la page HTML (anglais). */}
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`} // Application des polices locales et de l'anti-aliasing pour le texte.
			>
				{children}{" "}
				{/* Rendu des composants enfants (le contenu principal de l'application). */}
			</body>
		</html>
	);
}
